### ISSUE TITLE
Set up new machines

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/jsradicle#2]
`newMachine` creates new empty machines, but to send prelude and machine specific code, parsing whole files of Radicle code needs to be implemented.

**Comment by jkarni** [comment]
Why is parsing needed? Why not just send the text of the prelude?

**Comment by MeBrei** [comment]
I assumed I had to split it up into single commands as send takes an array of commands, but revisiting the code I see that the strings don't necessarily have to be a single command.
